</$objtype/mkfile

TARG=9de-shell
CFLAGS=-DUI9_NO_SYS_HEADERS -I../../include
OFILES=main.$O srv9p.$O

LIBS=-l9p -lthread

all:V: $TARG

$TARG: $OFILES
	$LD -o $TARG $OFILES $LIBS

%.6: %.c
	$CC $CFLAGS -c $stem.c

clean:V:
	rm -f *.$O $TARG
