</$objtype/mkfile

LIB=lib9deui.a
CFLAGS=-DUI9_NO_SYS_HEADERS -I../include

LIB=lib9deui.a

OFILES=\
	ui.$O \
	theme.$O \
	prim.$O \
	util.$O \
	sched.$O \
	frame.$O \
	icon.$O \
	layout.$O \
	widgets/button.$O \
	widgets/toggle.$O \
	widgets/slider.$O \
	widgets/segment.$O \
	widgets/textfield.$O \
	widgets/list.$O \
	widgets/progress.$O \
	widgets/dropdown.$O \

all:V: $LIB

$LIB: $OFILES
	$AR r $LIB $OFILES

%.6: %.c
	$CC $CFLAGS -c $stem.c

clean:V:
	rm -f *.$O $LIB widgets/*.$O
