#include <u.h>
#include <libc.h>

/*
 * 9de-session (early)
 *
 * Goal: keep session + autostart predictable.
 * This tool owns only:
 *   $home/lib/9de/defaults.rc  (shipped baseline)
 *   $home/lib/9de/config.rc    (user overrides; name=value only)
 *   $home/lib/9de/autostart.rc (generated from config)
 *
 * It does NOT try to be a full WM/compositor.
 *
 * Usage:
 *   9de-session init
 *   9de-session gen
 *   9de-session print
 */

static char*
home(void)
{
	char *h;

	h = getenv("home");
	if(h != nil && h[0] != 0)
		return h;
	h = getenv("HOME");
	if(h != nil && h[0] != 0)
		return h;
	return "/usr"; /* fallback; should not happen on 9front */
}

static int
ensure_dir(char *path)
{
	Dir *d;

	d = dirstat(path);
	if(d != nil){
		free(d);
		return 0;
	}
	return create(path, OREAD, DMDIR|0555) < 0 ? -1 : 0;
}

static int
writefile_atomic(char *path, char *data)
{
	char tmp[1024];
	int fd, n, len;

	snprint(tmp, sizeof tmp, "%s.tmp", path);

	fd = create(tmp, OWRITE, 0644);
	if(fd < 0) return -1;

	len = strlen(data);
	n = write(fd, data, len);
	close(fd);

	if(n != len){
		remove(tmp);
		return -1;
	}
	/* atomic-ish replace */
	remove(path);
	if(rename(tmp, path) < 0){
		/* rename may fail across mounts; fallback: copy */
		fd = open(tmp, OREAD);
		if(fd < 0) return -1;
		int out = create(path, OWRITE, 0644);
		if(out < 0){ close(fd); return -1; }
		char buf[4096];
		while((n = read(fd, buf, sizeof buf)) > 0)
			write(out, buf, n);
		close(out);
		close(fd);
		remove(tmp);
	}
	return 0;
}

static char*
readfile(char *path)
{
	int fd, n;
	char *buf;
	Dir *d;

	d = dirstat(path);
	if(d == nil) return nil;
	buf = malloc(d->length + 1);
	if(buf == nil){ free(d); return nil; }

	fd = open(path, OREAD);
	if(fd < 0){ free(d); free(buf); return nil; }

	n = read(fd, buf, d->length);
	close(fd);
	free(d);

	if(n < 0){ free(buf); return nil; }
	buf[n] = 0;
	return buf;
}

static int
cfgget_int(char *cfg, char *key, int def)
{
	char *p, *e;
	int klen;

	if(cfg == nil) return def;
	klen = strlen(key);

	for(p = cfg; *p; p++){
		/* line start or after \n */
		if(p != cfg && p[-1] != '\n')
			continue;
		if(*p == '#')
			continue;
		if(strncmp(p, key, klen) != 0)
			continue;
		if(p[klen] != '=')
			continue;
		e = strchr(p, '\n');
		if(e == nil) e = p + strlen(p);
		return atoi(p + klen + 1);
	}
	return def;
}

static void
paths(char *dir, int ndir, char *defaults, int ndef, char *config, int ncfg, char *auto1, int nauto)
{
	snprint(dir, ndir, "%s/lib/9de", home());
	snprint(defaults, ndef, "%s/defaults.rc", dir);
	snprint(config, ncfg, "%s/config.rc", dir);
	snprint(auto1, nauto, "%s/autostart.rc", dir);
}

static void
cmd_init(void)
{
	char dir[512], defaults[512], config[512], auto1[512];

	paths(dir, sizeof dir, defaults, sizeof defaults, config, sizeof config, auto1, sizeof auto1);

	if(ensure_dir(home()) < 0) sysfatal("ensure home: %r");
	/* ensure $home/lib and $home/lib/9de */
	{
		char libdir[512];
		snprint(libdir, sizeof libdir, "%s/lib", home());
		ensure_dir(libdir);
	}
	if(ensure_dir(dir) < 0) sysfatal("mkdir %s: %r", dir);

	/* shipped baseline defaults */
	writefile_atomic(defaults,
		"# 9DE defaults (shipped)\n"
		"start_shell=1
"
		"start_demo=1
"
		"ui_alpha=185\n"
	);

	/* user config (initially empty overrides) */
	if(access(config, AEXIST) < 0){
		writefile_atomic(config,
			"# 9DE user config (generated/owned by Control Center)\n"
			"# Put only name=value overrides here.\n"
			"\n"
		);
	}

	fprint(1, "9de-session: initialized in %s\n", dir);
}

static void
cmd_gen(void)
{
	char dir[512], defaults[512], config[512], auto1[512];
	char *dflt, *cfg;
	int start_shell, start_demo;

	paths(dir, sizeof dir, defaults, sizeof defaults, config, sizeof config, auto1, sizeof auto1);

	dflt = readfile(defaults);
	cfg = readfile(config);

	start_shell = cfgget_int(cfg, "start_shell", cfgget_int(dflt, "start_shell", 1));
	start_demo  = cfgget_int(cfg, "start_demo",  cfgget_int(dflt, "start_demo", 1));

	/* generate autostart */
	{
		char out[4096];
		\
snprint(out, sizeof out,
			"#!/bin/rc
"
			"# generated by 9de-session
"
			"
"
			"9dehome=%s/lib/9de
"
			"if(test -e $9dehome/defaults.rc) . $9dehome/defaults.rc
"
			"if(test -e $9dehome/config.rc)   . $9dehome/config.rc
"
			"
"
			"logdir=%s/lib/9de/log
"
			"rundir=%s/lib/9de/run
"
			"mkdir -p $logdir $rundir
"
			"
"
			"# runtime flags (no regen required)
"
			"shellflags=()
"
			"if(~ $start_demo 1) shellflags=(-d)
"
			"
"
			"if(~ $start_shell 1) 9de-shell $shellflags
"
			"
",
			home(), home(), home());
		if(writefile_atomic(auto1, out) < 0)
			sysfatal("write %s: %r", auto1);
	}
free(dflt);
	free(cfg);

	fprint(1, "9de-session: generated %s\n", auto1);
	fprint(1, "  start_shell=%d start_demo=%d\n", start_shell, start_demo);
}

static void
cmd_print(void)
{
	char dir[512], defaults[512], config[512], auto1[512];
	paths(dir, sizeof dir, defaults, sizeof defaults, config, sizeof config, auto1, sizeof auto1);

	fprint(1, "9DE paths:\n");
	fprint(1, "  %s\n  %s\n  %s\n", defaults, config, auto1);

	{
		char *a = readfile(defaults);
		if(a){ fprint(1, "\n--- defaults.rc ---\n%s", a); free(a); }
		a = readfile(config);
		if(a){ fprint(1, "\n--- config.rc ---\n%s", a); free(a); }
		a = readfile(auto1);
		if(a){ fprint(1, "\n--- autostart.rc ---\n%s", a); free(a); }
	}
}

void
main(int argc, char **argv)
{
	if(argc < 2)
		sysfatal("usage: 9de-session init|gen|print");

	if(strcmp(argv[1], "init") == 0)
		cmd_init();
	else if(strcmp(argv[1], "gen") == 0)
		cmd_gen();
	else if(strcmp(argv[1], "print") == 0)
		cmd_print();
	else
		sysfatal("unknown command: %s", argv[1]);

	exits(nil);
}
