</$objtype/mkfile

TARG=9de-dash
CFLAGS=-DUI9_NO_SYS_HEADERS -I../../include
OFILES=main.$O
LIBS=../../lib/lib9deui.a -ldraw -levent

all:V: $TARG

$TARG: $OFILES
	$LD -o $TARG $OFILES $LIBS

%.6: %.c
	$CC $CFLAGS -c $stem.c

clean:V:
	rm -f *.$O $TARG
